import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const sb=createClient('https://eovecucquasyqqxnqjdu.supabase.co','sb_publishable_PTvVnoUdxaQjut04ZuUVOg_myD9UNHJ');let user,profile,file;
const $=x=>document.getElementById(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function prof(n,w){let{data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!data){await sb.from('profiles').insert({id:user.id,display_name:n,whatsapp:w});data={display_name:n,whatsapp:w,role:'member'}}profile=data;$('who').textContent='@'+data.display_name;$('pname').value=data.display_name;$('pwa').value=data.whatsapp||'';$('role').textContent='Peran: '+data.role}
async function login(){let n=$('name').value.trim(),w=$('wa').value.trim(),e=$('email').value.trim(),p=$('pass').value;if(n.length<2||!e||p.length<6){$('status').textContent='Lengkapi nama, email, password minimal 6 karakter.';return}$('status').textContent='Memproses...';let r=await sb.auth.signInWithPassword({email:e,password:p});if(r.error){r=await sb.auth.signUp({email:e,password:p,options:{data:{display_name:n,whatsapp:w}}});if(r.error){$('status').textContent=r.error.message;return}if(!r.data.session){$('status').textContent='Akun dibuat. Verifikasi email jika diminta.';return}}user=r.data.user;await prof(n,w);$('login').classList.add('hidden');$('main').classList.remove('hidden');loadAll();sub()}
async function signed(m){let r=await sb.storage.from(m.bucket).createSignedUrl(m.path,3600);return r.data?.signedUrl}
async function upload(bucket,f){let ext=(f.name.split('.').pop()||'bin').toLowerCase(),path=user.id+'/'+crypto.randomUUID()+'.'+ext;let r=await sb.storage.from(bucket).upload(path,f,{contentType:f.type});if(r.error)throw r.error;let x=await sb.from('media').insert({owner_id:user.id,bucket,path,mime_type:f.type,size_bytes:f.size}).select().single();if(x.error)throw x.error;return x.data}
async function messages(){let r=await sb.from('messages').select('*,profiles:sender_id(display_name),media:media_id(*)').is('deleted_at',null).order('created_at');if(r.error)return;let a=[];for(let m of r.data||[]){let v='';if(m.media){let u=await signed(m.media);if(u)v=m.media.mime_type?.startsWith('video')?`<video controls src="${u}"></video>`:`<img src="${u}"><br><a href="${u}" target="_blank" download>Simpan</a>`}a.push(`<div class="msg ${m.sender_id===user.id?'mine':''}"><div class="meta">${esc(m.profiles?.display_name||'Anggota')} · ${new Date(m.created_at).toLocaleString('id-ID')}</div>${esc(m.body||'')}${v}</div>`)}$('messages').innerHTML=a.join('')||'<p>Belum ada pesan.</p>';$('messages').scrollTop=$('messages').scrollHeight}
async function send(){if(!$('text').value.trim()&&!file)return;let mid=null;try{if(file)mid=(await upload('chat-media',file)).id;let r=await sb.from('messages').insert({sender_id:user.id,body:$('text').value.trim()||null,media_id:mid});if(r.error)throw r.error;$('text').value='';file=null;$('chatFile').value=''}catch(e){alert(e.message)}}
async function gallery(){let r=await sb.from('gallery').select('*,media:media_id(*),profiles:uploader_id(display_name)').order('created_at',{ascending:false});if(r.error)return;let a=[];for(let g of r.data||[]){let u=await signed(g.media);if(u)a.push(`<div class="media">${g.media.mime_type?.startsWith('video')?`<video controls src="${u}"></video>`:`<img src="${u}">`}<div>${esc(g.caption||'')}<br><small>${esc(g.profiles?.display_name||'')}</small><a href="${u}" target="_blank" download>Simpan</a></div></div>`)}$('grid').innerHTML=a.join('')||'<p>Galeri kosong.</p>'}
async function addGallery(){let f=$('galleryFile').files[0];if(!f)return;try{let m=await upload('gallery-media',f),r=await sb.from('gallery').insert({uploader_id:user.id,media_id:m.id,caption:$('caption').value.trim()});if(r.error)throw r.error;$('caption').value='';$('galleryFile').value='';gallery()}catch(e){alert(e.message)}}
async function payments(){let r=await sb.from('dues_donations').select('*').eq('member_id',user.id).order('created_at',{ascending:false});$('payments').innerHTML=(r.data||[]).map(x=>`<div class="card" style="padding:10px;margin:7px 0"><b>${x.kind}</b> · Rp ${Number(x.amount).toLocaleString('id-ID')}<br>${esc(x.note||'')} · ${x.status}</div>`).join('')}
async function trips(){let r=await sb.from('trips').select('*').order('event_date');$('tripList').innerHTML=(r.data||[]).map(x=>`<div class="card" style="padding:10px;margin:7px 0"><b>${esc(x.title)}</b><br>📍${esc(x.location||'-')} 📅${x.event_date||'-'}<br>${esc(x.description||'')}</div>`).join('')}
async function loadAll(){await messages();await gallery();await payments();await trips()}
function sub(){sb.channel('chat').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},messages).subscribe()}
$('loginBtn').onclick=login;$('logout').onclick=()=>sb.auth.signOut().then(()=>location.reload());$('pick').onclick=()=>$('chatFile').click();$('chatFile').onchange=e=>file=e.target.files[0];$('send').onclick=send;$('gallerySend').onclick=addGallery;$('pay').onclick=async()=>{let r=await sb.from('dues_donations').insert({member_id:user.id,kind:$('kind').value,amount:Number($('amount').value),note:$('note').value});if(r.error)alert(r.error.message);else payments()};$('tripAdd').onclick=async()=>{let r=await sb.from('trips').insert({title:$('tripTitle').value,location:$('tripLoc').value,event_date:$('tripDate').value||null,estimated_cost:$('tripCost').value?Number($('tripCost').value):null,description:$('tripDesc').value,created_by:user.id});if(r.error)alert(r.error.message);else trips()};$('saveProfile').onclick=async()=>{let r=await sb.from('profiles').update({display_name:$('pname').value,whatsapp:$('pwa').value,updated_at:new Date().toISOString()}).eq('id',user.id);if(r.error)alert(r.error.message);else prof($('pname').value,$('pwa').value)};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(b.dataset.t).classList.remove('hidden')});let s=await sb.auth.getSession();if(s.data.session){user=s.data.session.user;await prof();$('login').classList.add('hidden');$('main').classList.remove('hidden');loadAll();sub()}
